name: Run Updater Script

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每3天的00:00执行一次
  workflow_dispatch:

jobs:
  run-updater:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist updater\requirements.txt pip install -r updater\requirements.txt

      - name: Set up Git for commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase false
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Run updater script
        run: python updater\main.py